name: airo_control_interface
root: ./
startup_window: control_interface
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
        - ./wait_for_ros.sh; roslaunch airo_control mavros_px4.launch
        - ./wait_for_ros.sh; roslaunch airo_control vrpn.launch
  - control_interface:
      layout: tiled
      panes:
        - ./wait_for_ros.sh; roslaunch airo_control fsm.launch
        - ./wait_for_ros.sh; roslaunch airo_trajectory example_mission_node.launch