pose_topic: /mavros/local_position/pose
twist_topic: /mavros/local_position/velocity_local
yaml_name: /config/gazebo_param.yaml
message_timeout: 0.5
motor_speedup_time: 5.0
takeoff_height: 1.0
takeoff_land_speed: 0.3
reject_takeoff_twist_threshold: 0.15
hover_max_velocity: 2.5
hover_max_rate: 2.5
check_safety_volumn: true
safety_volumn: [-10.0, 10.0, -10.0, 10.0, -10, 4.0]
without_rc: true
throttle_channel: 4
yaw_channel: 3
pitch_channel: 1
roll_channel: 2
fsm_channel: 5
command_channel: 7
reboot_channel: 8
reverse_throttle: false
reverse_yaw: false
reverse_pitch: false
reverse_roll: false
switch_threshold: 0.75
joystick_deadzone: 0.10
check_centered_threshold: 0.3
hover_thrust: 0.5661135083436966
tau_phi: 0.1970738954513166
tau_theta: 0.1952294046513412
tau_psi: 0.7887078738298164