message_timeout: 0.5
motor_speedup_time: 5.0
takeoff_height: 1.0
takeoff_land_speed: 0.3
reject_takeoff_twist_threshold: 0.15
hover_max_velocity: 0.5
hover_max_rate: 0.5
check_safety_volumn: true
safety_volumn: [-2.0, 2.0, -2.0, 2.0, -10, 4.0]
without_rc: true
throttle_channel: 4
yaw_channel: 3
pitch_channel: 1
roll_channel: 2
fsm_channel: 5
command_channel: 7
reboot_channel: 8
reverse_throttle: false
reverse_yaw: false
reverse_pitch: false
reverse_roll: false
switch_threshold: 0.75
joystick_deadzone: 0.10
check_centered_threshold: 0.2
hover_thrust: 0.5661515682935715
tau_phi: -0.0008555501656665047
tau_theta: -0.1139583510895322
tau_psi: 1.694830355146349