pub_debug: false
enable_thrust_model: false
apply_observer: true

# system parameters
hover_thrust: 0.448863 
enable_preview: true
tau_phi: 0.133616
tau_theta: 0.13068
tau_psi: 0.411795

# # conservative costs
# diag_cost_x:
#   - 60.0
#   - 60.0
#   - 60.0
#   - 30.0
#   - 30.0
#   - 30.0
#   - 10.0
#   - 10.0

# diag_cost_u:
#   - 200.0
#   - 1000.0
#   - 1000.0
  
# diag_cost_xn:
#   - 60.0
#   - 60.0
#   - 60.0
#   - 30.0
#   - 30.0
#   - 30.0
#   - 10.0
#   - 10.0

# aggressive costs
diag_cost_x:
  - 200.0
  - 200.0
  - 200.0
  - 80.0
  - 80.0
  - 120.0
  - 10.0
  - 10.0

diag_cost_u:
  - 20.0
  - 1000.0
  - 1000.0
  
diag_cost_xn:
  - 200.0
  - 200.0
  - 200.0
  - 80.0
  - 80.0
  - 120.0
  - 10.0
  - 10.0